# Generated by Django 3.2.7 on 2021-10-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_comment_image_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
