# Generated by Django 3.2.7 on 2021-10-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_image_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='picture',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='commerce_1_Diagram.drawio.png', upload_to='images/'),
        ),
    ]
